import Topo from "@/components/Topo";
import "./globals.css";
import { CarrinhoProvider } from "@/context/CarrinhoContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <CarrinhoProvider>
        {children}
        </CarrinhoProvider>
      </body>
    </html>
  );
}
